
substitutions:
  bmp280_sda: "GPIO21"
  bmp280_scl: "GPIO22"
  bmp280_address: "0x76" # This might vary by mfr. (0x76 or 0x77)
  bmp280_interval: "15s"

i2c:
  sda: ${bmp280_sda}
  scl: ${bmp280_scl}
  scan: true
  id: i2c_bus_a
  
sensor:
  - platform: bmp280
    i2c_id: i2c_bus_a
    address: ${bmp280_address}
    update_interval: ${bmp280_interval}
    iir_filter: 4x

    temperature:
      name: "Ambient Temperature"
      id: ambient_temperature
      oversampling: 16x
      device_class: temperature
    
    pressure:
      name: "Atmospheric Pressure"
      id: ambient_pressure
      device_class: atmospheric_pressure

  - platform: template
    name: "Altitude"
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(ambient_temperature).state + 273.15) / 0.0065) *
        (powf((STANDARD_SEA_LEVEL_PRESSURE / id(ambient_pressure).state), 0.190234) - 1); // in meters
    update_interval: 15s
    icon: 'mdi:signal'
    unit_of_measurement: 'm'