# NOTE: This file is not a stand-alone package. It is part of
# a 'root' device template and expects the substitutions that
# are hereby referenced to be defined by its parent.

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    
